### ISSUE TITLE
Which TRY traits will we include?

### ISSUE THREAD

**Issue by scisus** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#34]
Decide which traits will be included in the analysis.

**Comment by BenMerSci** [comment]
We suggested them to be like more observable traits.
I think we said like 5 traits?
I think SLA was already one we decided.
I would also suggest we go for the trait with the more observation on TRY, otherwise we might end up with very few species in the analysis (some traits don't have much observation)

**Comment by BenMerSci** [comment]
Some that I think could be interesting:
-  Seed dry mass
- Plant woodiness
- Plant height vegetative
- Leaf thickness
- Leaf phenols content per leaf dry mass ( proxy for palatable/"toxic"?)
- Leaf petiole length
- Leaf nitrogen (N) content per leaf dry mass

**Comment by scisus** [comment]
Do phenols or nitrogen contribute to the appearance of the community?

**Comment by scisus** [comment]
Closing this issue - continuing in #49
